<?php
/**
 * Copyright Total Processing. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Process error template
 *
 * @var \TotalProcessing\Opp\Block\Error $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div role="alert" class="messages">
    <div class="message-error error message">
        <div><?= /* @noEscape */ $block->getErrorMessage(); ?></div>
    </div>
</div>
<p><?= /* @noEscape */ __('The page will be refreshed after 5 seconds.') ?></p>
<?php $scriptString = <<<script
let iframe = window.parent.document.getElementById("totalprocessing_opp_iframe");
if (iframe) {
    iframe.style.height = "100px";
}
setTimeout(function() {
    window.parent.location.reload();
}, 5000);
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
