<?php
/**
 * Copyright © Total Processing. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var TotalProcessing\Opp\Block\Frame $block
 */
?>
<script src="<?php echo $block->getPaymentWidgetsUrl(); ?>"></script>
<script>
    function postMessage(iframeDoc, iframeHeight, isPlaceOrderVisible) {
        let event;
        let data = {
            "iframeDoc": iframeDoc,
            "iframeHeight": iframeHeight,
            "isVisible": isPlaceOrderVisible,
            "placeOrder": false
        }

        if (typeof window.CustomEvent === "function") {
            event = new CustomEvent('iframe', {detail: data});
        } else {
            event = document.createEvent('Event');
            event.initEvent('iframe', true, true);
            event.detail = data
        }

        window.parent.document.dispatchEvent(event);
    }

    function getHeight(isAfterSubmit = false) {
        let height = Math.max(
            document.body.scrollHeight,
            document.body.offsetHeight,
            document.documentElement.clientHeight,
            document.documentElement.scrollHeight,
            document.documentElement.offsetHeight
        );

        if (isAfterSubmit) {
            height = Math.round(height * 1.5);
        }

        height += 50;

        return Math.round(height);
    }

    var wpwlOptions = {
        onReady: function() {
            // inject custom script from admin panel
            <?php echo $block->getOnReadyCustomScript() ?>

            // inject custom css from admin panel
            $("head link[rel='stylesheet']").last().after(
                "<style rel='stylesheet' type='text/css' media='all'>"+
                "<?php echo $block->getStyleOptionsCustomIframeCss().' '.$block->getStyleOptionsDefault() ?>" +
                "<\/script>"
            );
            let __self = this;

            <?php if ($block->isVaultEnabled() && !$block->isSchedulerActive()): ?>
            $('form.wpwl-form-card').find('.wpwl-button').before(
                '<div class="customLabel"><?php echo __("Store payment details?")?></div>' +
                '<div class="customInput"><input type="checkbox" name="createRegistration" value="true" /></div>'
            );
            <?php endif; ?>

            $('button').on("click.wpwlEvent", function () {
                setTimeout(function () { postMessage(__self.document, getHeight(), false); }, 100);
            });

            $('.wpwl-container-card, .wpwl-container-registration')
                .find('.wpwl-button-pay')
                .html('<?php echo $block->getPaymentBtnText();?>');

            postMessage(this.document, 0, false);
        },
        onAfterSubmit: function () {
            postMessage(this.document, getHeight(true), false);
        },
        onReadyIframeCommunication: function () {
            postMessage(this.document, getHeight(), false);
        },
        registrations: {
            requireCvv: true,
            hideInitialPaymentForms: true
        },
        brandDetection: true,
        brandDetectionType: "binlist",
        brandDetectionPriority: [<?php echo $block->getBrandsDetectionString() ?> ],
        disableSubmitOnEnter: true,
        locale: "<?php echo $block->getLocale(); ?>",
        paymentTarget: "totalprocessing_opp_iframe",
        shopperResultTarget: "totalprocessing_opp_iframe",
        style: "<?php echo $block->getStyleOption(); ?>"
    }
</script>
<form
    class="paymentWidgets"
    action="<?php echo $block->getRedirectUrl();?>"
    data-brands="<?php echo $block->getBrands(); ?>">
</form>
