<?php
/**
 * Copyright © Total Processing. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var TotalProcessing\Opp\Block\System\Config\RegisterMerchantButton $block
 */
?>
<script>
    require(
        [
            'jquery',
            'prototype'
        ],
        function(
            $
        ) {
            $(document).ready(function () {
                $("input[id$='_<?= $block->getMerchantIdentifierId(); ?>']").attr('readonly', true);
            });

            $("#<?= $block->getButtonId(); ?>").click(function (e) {
                e.preventDefault();

                $('body').trigger('processStart');

                let env = $("select[id$='<?= $block->getEnvironmentId(); ?>']").val(),
                    registerUrl = $("input[id$='" + env + "_" + env + "_<?= $block->getRegisterUrlId(); ?>']").val(),
                    entityId = $("input[id$='" + env + "_" + env + "_<?= $block->getEntityId(); ?>']").val(),
                    accessToken = $("input[id$='" + env + "_" + env + "_<?= $block->getAccessTokenId(); ?>']").val(),
                    domainNames = $("input[id$='" + env + "_" + env + "_<?= $block->getDomainNamesId(); ?>']").val(),
                    displayName = $("input[id$='" + env + "_" + env + "_<?= $block->getDisplayNamesId(); ?>']").val(),
                    merchantIdentifier = $("input[id$='" + env + "_" + env + "_<?= $block->getMerchantIdentifierId(); ?>']");


                let data = {
                    registerUrl: registerUrl,
                    environment: env,
                    entityId: entityId,
                    accessToken: accessToken,
                    domainNames: domainNames,
                    displayName: displayName
                };

                $("#" + merchantIdentifier.attr('id') + "-error").remove();
                merchantIdentifier.val('');

                let html = merchantIdentifier.parent().html();

                $.ajax({
                    url: "<?= $block->getAjaxUrl(); ?>",
                    method: "POST",
                    data: data,
                    dataType: "json",

                    /** @inheritdoc */
                    success: function (result) {
                        if (result.status) {
                            merchantIdentifier.val(result.merchantIdentifier);
                        } else {
                            html += '<label for="' + merchantIdentifier.attr('id') +'" generated="true" ' +
                                'class="mage-error" id="' + merchantIdentifier.attr('id') + '-error" style="display: ' +
                                'block;"><?= /* @noEscape */ __("Merchant registration error"); ?></label>';
                            merchantIdentifier.parent().html(html);
                        }
                        $('body').trigger('processStop');
                    },

                    /** @inheritdoc */
                    error: function (jqXHR) {
                        html += '<label for="' + merchantIdentifier.attr('id') +'" generated="true" ' +
                            'class="mage-error" id="' + merchantIdentifier.attr('id') + '-error" style="display: ' +
                            'block;"><?= /* @noEscape */ __("Merchant registration error");?></label>';
                        merchantIdentifier.parent().html(html);

                        $('body').trigger('processStop');
                    },

                    /** @inheritdoc */
                    complete: function () {
                        $('body').trigger('processStop');
                    }
                });
            });
        }
    );
</script>
<?= /* @noEscape */ $block->getButtonHtml(); ?>
